# Generated by Django 5.1.2 on 2024-12-16 17:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unique_id", models.CharField(max_length=36, unique=True)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="student_files/"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="student_images/"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("embedding", models.JSONField(blank=True, null=True)),
                ("thumbnail", models.CharField(blank=True, max_length=255, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("has_downloaded", models.BooleanField(default=False)),
                (
                    "file_type",
                    models.CharField(
                        choices=[("image", "Image"), ("document", "Document")],
                        default="image",
                        max_length=20,
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Student File",
                "verbose_name_plural": "Student Files",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ImageMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_path", models.CharField(max_length=255)),
                ("embedding", models.JSONField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "parent_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_metadata",
                        to="image_search.studentimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Image Metadata",
                "verbose_name_plural": "Image Metadata",
            },
        ),
        migrations.CreateModel(
            name="TextChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("start_char", models.IntegerField(blank=True, null=True)),
                ("end_char", models.IntegerField(blank=True, null=True)),
                ("embedding", models.JSONField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "parent_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="text_chunks",
                        to="image_search.studentimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Text Chunk",
                "verbose_name_plural": "Text Chunks",
            },
        ),
    ]
